services:
    psql:
        image: postgres:17.5-alpine
        container_name: psql_db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
