services:
    mysql:
        image: mysql:9.1.0
        container_name: mysql_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mysql
            MYSQL_USER: mysql
            MYSQL_PASSWORD: mysql
        volumes:
            - mysqldata:/var/lib/mysql
volumes:
    mysqldata:
