services:
    redis:
        image: redis:7-alpine
        container_name: redis-server
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
        environment:
            - REDIS_REPLICATION_MODE=master
        networks:
            - redis-network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 3s
            retries: 3

    redis-commander:
        image: rediscommander/redis-commander:latest
        container_name: redis-commander
        restart: unless-stopped
        depends_on:
            - redis
        ports:
            - "8081:8081"
        environment:
            - REDIS_HOSTS=local:redis:6379
        networks:
            - redis-network

volumes:
    redis_data:
        driver: local

networks:
    redis-network:
        driver: bridge
